services:
  mysql-service:
    image: mysql:9.6.0 #This is the official MySQL image from Docker Hub. In the future we will build our own image in the repository.
    container_name: mysql-service
    healthcheck: #Necessary to make sure that the webserver only starts after the database is running.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 45s
      timeout: 10s
      retries: 3
    environment: #These are the variables needed for someone to access the MySQL database and MySQL also needs these variables to be set up correctly. 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: #The volume basically defines a place on the host machine to persist the data from the MySQL database. So if the container stops the data will still remain on the host machine.
      - db_data:/var/lib/mysql
    networks: #Defines the network in Docker that MySQL and the webserver will be connected to in order to communicate with each other (it's just an arbitrary name for the network)
      - minitwit-network
    restart: unless-stopped #This makes sure that the container will be restarted if it stops for some reason.

  webserver:
    image: ${DOCKER_USERNAME}/minitwit:latest #Repository name + tag of the image on Docker Hub.
    environment: #These are the environment variables that the webserver needs to run and connect to the MySQL database.
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Server=mysql-service;database=${MYSQL_DATABASE}; User=${MYSQL_USER};Password=${MYSQL_PASSWORD};"
    ports:
      - "8080:8080"
    depends_on: #Makes sure that the webserver only starts after the healthcheck succeeds (see healthcheck in mysql-service))
      mysql-service: 
        condition: service_healthy
        
    networks:
      - minitwit-network
    restart: unless-stopped #This makes sure that the container will be restarted if it stops for some reason.
  
  # Prometheus port should not be exposed
  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./Moniter/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - minitwit-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - minitwit-network
  
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - minitwit-network

  alloy:
    image: grafana/alloy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy_data:/alloy
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - minitwit-network



volumes: #The volume that the mysql-service refers to. "local" means it will be stored on the host machine.
  db_data:
    driver: local
  prometheus_data:
  grafana_data:
  loki_data:
  alloy_data:

networks: #Again just an arbitrary name for the network that the services will be connected to.
  minitwit-network:
    name: "minitwit-network"
    external: false 
