services:
  webserver1:
    image: ${DOCKER_USERNAME}/minitwit:latest #Repository name + tag of the image on Docker Hub.
    environment: #These are the environment variables that the webserver needs to run and connect to the MySQL database.
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=${MYSQL_HOST}; Port=${MYSQL_PORT}; database=${MYSQL_DATABASE}; User=${MYSQL_USER};Password=${MYSQL_PASSWORD}; SslMode=Required;"
    ports:
      - "8081:8080"
    networks:
      minitwit-network:
        aliases:
          - webserver
    restart: unless-stopped #This makes sure that the container will be restarted if it stops for some reason.
  webserver2:
    image: ${DOCKER_USERNAME}/minitwit:latest #Repository name + tag of the image on Docker Hub.
    environment: #These are the environment variables that the webserver needs to run and connect to the MySQL database.
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=${MYSQL_HOST}; Port=${MYSQL_PORT}; database=${MYSQL_DATABASE}; User=${MYSQL_USER};Password=${MYSQL_PASSWORD}; SslMode=Required;"
    ports:
      - "8082:8080"
    networks:
      minitwit-network:
        aliases:
          - webserver
    restart: unless-stopped #This makes sure that the container will be restarted if it stops for some reason.
  
  # Prometheus port should not be exposed
  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./Moniter/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - minitwit-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - minitwit-network
  
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    restart: unless-stopped
    networks:
      minitwit-network:
        aliases:
          - loki

  alloy:
    image: grafana/alloy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy_data:/alloy
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - minitwit-network



volumes: #The volume that the mysql-service refers to. "local" means it will be stored on the host machine.
  db_data:
    driver: local
  prometheus_data:
  grafana_data:
  loki_data:
  alloy_data:

networks: #Again just an arbitrary name for the network that the services will be connected to.
  minitwit-network:
    name: "minitwit-network"
    external: false 
