global:
  scrape_interval: #defaults to 15s
  external_labels:
    monitor: 'minitwit'

scrape_configs:
  - job_name: "minitwit"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["webserver:8080"] #URL for the webapp?
      #Multiple targets can be added under one label, or mutliple targets with their own label in the same config