global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'blue_servers'
    static_configs:
      - targets: ['blueserver1:8080', 'blueserver2:8080']
  
  - job_name: 'green_servers'
    static_configs:
      - targets: ['greenserver1:8080', 'greenserver2:8080']