#!/usr/bin/env python3
import argparse
import json
import os
import sys
import urllib.request

def assign(ip, droplet_id, token):
    url = "https://api.digitalocean.com/v2/reserved_ips/{}/actions".format(ip)
    data = json.dumps({"type": "assign", "droplet_id": int(droplet_id)}).encode()
    req = urllib.request.Request(url, data=data, headers={
        "Authorization": "Bearer {}".format(token),
        "Content-Type": "application/json"
    })
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())

parser = argparse.ArgumentParser()
parser.add_argument("ip")
parser.add_argument("droplet_id")
args = parser.parse_args()

token = os.environ.get("DO_TOKEN")
if not token:
    print("DO_TOKEN not set", file=sys.stderr)
    sys.exit(1)

print(json.dumps(assign(args.ip, args.droplet_id, token)))
