name: Linting and formatting

on:
  push:
  pull_request:

  linting_formatting:
    jobs:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Check formatting
          uses: actions/checkout@v4
          run: |
            dotnet tool restore
            dotnet csharpier check . --config-path "./config/dotnet-tool.json"