name: scp files to VMs

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      host1:
        required: true
        type: string
      host2:
        required: true
        type: string

jobs:
  scp-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload docker-compose
        uses: appleboy/scp-action@v1
        with:
          host: ${{ inputs.host1 }},${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: docker-compose.yml
          target: /root

      - name: Upload prometheus.yml file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ inputs.host1 }},${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: Moniter/Prometheus/prometheus.yml
          target: /root

      - name: Upload config.alloy file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ inputs.host1 }},${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: alloy/config.alloy
          target: /root

      - name: Upload loki-config.yml file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ inputs.host1 }},${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: loki/loki-config.yml
          target: /root

      - name: Create .env file vm1
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ inputs.host1 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cat << EOF > /root/.env
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            EOF

      - name: Create .env file vm2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cat << EOF > /root/.env
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            EOF

      - name: Upload deploy.sh
        uses: appleboy/scp-action@v1
        with:
          host: ${{ inputs.host1 }},${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: scripts/deploy.sh
          target: /root

      - name: Upload nginx config
        uses: appleboy/scp-action@v1
        with:
          host: ${{ inputs.host1 }},${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: nginx/devopsducks.studio
          target: /root

      - name: Install nginx config
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ inputs.host1 }},${{ inputs.host2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo cp /root/nginx/devopsducks.studio /etc/nginx/sites-available/devopsducks.studio
            sudo ln -sf /etc/nginx/sites-available/devopsducks.studio /etc/nginx/sites-enabled/devopsducks.studio
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo nginx -t && sudo systemctl reload nginx
